export const DESKTOP_ERROR_CODES = Object.freeze({
    validation: 'VALIDATION_ERROR',
    notFound: 'NOT_FOUND',
    conflict: 'CONFLICT',
    revisionConflict: 'REVISION_CONFLICT',
    cancelled: 'CANCELLED',
    provider: 'PROVIDER_ERROR',
    agentCredentialMissing: 'AGENT_CREDENTIAL_MISSING',
    agentRuntimeStartFailed: 'AGENT_RUNTIME_START_FAILED',
    agentRuntimeUnreachable: 'AGENT_RUNTIME_UNREACHABLE',
    agentSessionNotFound: 'AGENT_SESSION_NOT_FOUND',
    agentSessionProjectMismatch: 'AGENT_SESSION_PROJECT_MISMATCH',
    agentPromptRejected: 'AGENT_PROMPT_REJECTED',
    agentCancelRejected: 'AGENT_CANCEL_REJECTED',
    agentStreamDisconnected: 'AGENT_STREAM_DISCONNECTED',
    dataCorrupt: 'DATA_CORRUPT',
    permissionDenied: 'PERMISSION_DENIED',
    internal: 'INTERNAL_ERROR',
});
